### ISSUE TITLE
Azure Studio: cannot run Visualizer

### ISSUE THREAD

**Issue by Oleg26Dev** [microsoft/SandDance#120] opened 2019-10-19 11:28 UTC
I run the Azure Data Studio, connected to PostgreSQL database. All works fine. 
I'd like to create some SandDance charts using data from a database.

Then run query, did as it is written in the doc: 
"Starting from a SQL query window, execute a query to get a results grid. Click the Visualizer icon on the right side of the Results pane."

But when I click Visualizer icon I have no any results. What I do wrong?

**Comment by danmarshall** [comment] 2019-10-19 13:25
Hello, I think this issue is a duplicate of #33 . Still under investigation...
I am going to close this issue and we can track it in #33, thanks.

**Closed by danmarshall** 2019-10-19 13:25 UTC
