### ISSUE TITLE
3D Scatter Chart Backwards Z Labels 

### ISSUE THREAD

**Issue by chrisheltzel** [microsoft/SandDance#562] opened 2022-12-27 21:45 UTC
3D Scatter chart Z axis labels are order opposite of data.  In the attached image CoF values are plotted on Z axis correctly with 1s at bottom and 5s at top, but the labels show 5 at bottom and 1 at top.  The displayed tooltip shows the value of CoF 5 at the top right next to the label 1.
I am using version 4.0.0 in Power BI 2.112.603.0 64-bit (December 2022)

![3dScatterZLabel](https://user-images.githubusercontent.com/50672704/209724279-69a4ba3d-1aee-40c0-a6f2-0257e313d608.png)

**Comment by danmarshall** [comment] 2022-12-28 04:16
Thanks for posting. I believe this is a duplicate of #546 . This is fixed in the codebase, but not yet deployed to PowerBI. (They are working on a new deployment model, so it may take some time until you get the new version.)

**Closed by danmarshall** 2022-12-28 04:16 UTC
