### ISSUE TITLE
Numerical values are sorted as strings

### ISSUE THREAD

**Issue by steel3d** [microsoft/SandDance#262] opened 2020-07-31 03:12 UTC
I'm using VS Code, opened the titanic csv downloaded from here https://www.openml.org/d/40945, and if I set "fare" as one of the axes, values will be all mixed up: 49.5, 5, 50, .. 512.32, 52, etc. 

I think the fundamental issue is that there's no way to specify data type per column. Maybe it would work if I hand sanitized the csv first, but that seems to defeat half of the purpose of this tool: to explore unknown data sets. Would it make sense to add type casting and other sanitization features?

Edit: I used another tool - CSV Edit - to find and remove a single question mark, and now fare is recognized as numeric.

**Comment by ackalker** [comment] 2020-09-11 19:14
I'm having a similar issue with a CSV file containing columns of numerical values which are wrapped in quotes to protect the `,` decimal separator, which is used in my country. There is no way to sanitize this data short of converting all of it to use US `.` decimal separators, which inevitably affects how the data is displayed in visualizations as well. This again defeats most of the purpose of SandDance.
We need a way to specify column data types, urgently!

**Comment by danmarshall** [comment] 2023-01-05 00:12
Duplicate of #270

**Closed by danmarshall** 2023-01-05 00:12 UTC
Labels: enhancement
